Repository CloudsBlaze/portfolio, pull requests merged in 2023-12, with the labels that each got.

#40 adding favicon to the site
  static/img/favicon/browserconfig.xml
  static/img/favicon/favicon.ico
  static/img/favicon/safari-pinned-tab.svg
  static/img/favicon/site.webmanifest
  templates/base.html
Labels: enhancement

#42 home page changes
  static/compiled_css/custom.min.css
  static/compiled_css/custom.min.css.map
  static/css/main.css
  static/scss/custom.scss
  templates/_partiales/footer.html
  templates/_partiales/headers.html
  templates/_partiales/nav_bar.html
  templates/frontend/_partiales/about_us.html
  templates/frontend/_partiales/best_clients.html
  templates/frontend/_partiales/blog_posts.html
  templates/frontend/_partiales/built_for.html
  templates/frontend/_partiales/case_study.html
  templates/frontend/_partiales/ceo_video.html
  templates/frontend/_partiales/certifications.html
  templates/frontend/_partiales/cta.html
  templates/frontend/_partiales/hero_section.html
  templates/frontend/_partiales/our_service.html
  templates/frontend/_partiales/partner_stories.html
  templates/frontend/_partiales/reviews.html
  templates/frontend/_partiales/tech_stack.html
  templates/frontend/_partiales/testimonials.html
  templates/frontend/index.html
  website/settings.py
Labels: enhancement

#43 41 home page layout new
  static/css/main.css
  templates/_partiales/headers.html
  templates/_partiales/nav_bar.html
  templates/frontend/_partiales/hero_section.html
  templates/frontend/_partiales/our_team.html
  templates/frontend/_partiales/popular_services.html
  templates/services/_partiales/about_us.html
  templates/services/_partiales/case_study.html
  templates/services/_partiales/hero_section.html
  templates/services/_partiales/partner_stories.html
  templates/services/index.html
Labels: enhancement

#44 fix the responsive issues in the home page
  static/css/main.css
  templates/_partiales/footer.html
  templates/_partiales/nav_bar.html
  templates/frontend/_partiales/about_us.html
  templates/frontend/_partiales/blog_posts.html
  templates/frontend/_partiales/built_for.html
  templates/frontend/_partiales/certifications.html
  templates/frontend/_partiales/hero_section.html
  templates/frontend/_partiales/partner_stories.html
Labels: minor fix

#45 add service sections
  templates/services/_partiales/about_us.html
  templates/services/_partiales/best_clients.html
  templates/services/_partiales/hero_section.html
  templates/services/_partiales/popular_services.html
  templates/services/_partiales/we_do.html
  templates/services/index.html
Labels: enhancement, minor fix
